### ISSUE TITLE
2 micro rkv per test fails, gets "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/regionless-storage-service#57]
this bug was found when running perf test with 2 micro configuration.

The config.json file used in this case is
```json
{
  "ConsistentHash": "rendezvous",
  "BucketSize": 10,
  "ReplicaNum": 2,
  "StoreType": "redis",
  "Concurrent": true,
  "Stores": [
    {
      "Name": "hwperf-0824-1-rkv-lab-si-0",
      "Host": "54.219.184.67",
      "Port": 6666
    },
    {
      "Name": "hwperf-0824-1-rkv-lab-si-1",
      "Host": "54.183.189.182",
      "Port": 6666
    },
    {
      "Name": "hwperf-0824-1-rkv-lab-si-2",
      "Host": "35.89.67.43",
      "Port": 6666
    },
    {
      "Name": "hwperf-0824-1-rkv-lab-si-3",
      "Host": "35.90.217.98",
      "Port": 6666
    }
  ]
}
``` 
rkv server log has error message:
```text
...
2022/08/24 17:20:56 http: panic serving 35.90.155.56:35186: runtime error: invalid memory address or nil pointer dereference
goroutine 2522 [running]:
net/http.(*conn).serve.func1(0xc000089720)
	/usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x7655c0, 0xa011f0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000232180, 0x0, 0x0, 0x0)
	/home/ubuntu/regionless-storage-service/vendor/go.opentelemetry.io/otel/sdk/trace/span.go:402 +0x345
panic(0x7655c0, 0xa011f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
main.(*KeyValueHandler).createKV(0xc0000c6800, 0x83b590, 0xc00025b880, 0xc0001ec100, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/regionless-storage-service/cmd/http/main.go:221 +0x25d
main.(*KeyValueHandler).ServeHTTP(0xc0000c6800, 0x83b590, 0xc00025b880, 0xc0001ec100)
	/home/ubuntu/regionless-storage-service/cmd/http/main.go:105 +0x3c5
net/http.(*ServeMux).ServeHTTP(0xa12100, 0x83b590, 0xc00025b880, 0xc0001ec100)
	/usr/local/go/src/net/http/server.go:2428 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00025a0e0, 0x83b590, 0xc00025b880, 0xc0001ec100)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000089720, 0x83bc00, 0xc000394b00)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x39b
...
```

jaeger trace shows 1 span with exception log:
![Screenshot from 2022-08-24 11-14-06](https://user-images.githubusercontent.com/16367914/186492926-406d4e4c-f490-46d0-b89c-c0df6c3211ef.png)

## How to reproduce
```bash
cd scritpts
./select_config.sh 2 micro
./setup_test_lab.sh si_def.json
```

**Comment by h-w-chen** [comment]
further investigation reveals that the config.json file lacks local/neighbor/remote label for stores

**Comment by h-w-chen** [comment]
latest code change categories nodes by probing the lateny; so no need to put explicit local/neighbor/remote. not an issue anymore.
